//! Downloads the published per-PDF indexes from the TuneCall server.
//!
//! Fetched over `https://` with `reqwest` (rustls + bundled CA roots, so TLS
//! works on Android too) and streamed to disk. The caller drives this on
//! Slint's event loop via `async-compat`.
//!
//! The server holds two manifests (one filename per line) plus the files:
//! * `index.txt` — the `<book>.db` indexes, auto-generated by
//!   `indexer/upload-indexes.sh`. Fetched into the download folder.
//! * `pdfindex.txt` — public-domain `<book>.pdf` books, maintained by hand.
//!   Fetched into `pdf_dir` (the same place the user installs their own books),
//!   so the loader pairs each with its `.db` exactly as a user-installed PDF.
//!   Optional: a missing manifest just means there are none.

use std::fs::File;
use std::io::Write;
use std::path::Path;

use anyhow::Result;
use futures_util::StreamExt;
use reqwest::Client;

use crate::storage;

const BASE_URL: &str = "https://www.davidfaure.fr/tunecall";

/// Stream `url` to `path` via a temporary `.part` file (so a failed download
/// never leaves a truncated index in place).
async fn download_to(client: &Client, url: &str, path: &Path) -> Result<()> {
    let response = client.get(url).send().await?.error_for_status()?;
    let mut stream = response.bytes_stream();
    let tmp = path.with_extension("part");
    {
        let mut file = File::create(&tmp)?;
        while let Some(chunk) = stream.next().await {
            file.write_all(&chunk?)?;
        }
    }
    std::fs::rename(&tmp, path)?;
    Ok(())
}

/// Download both manifests and every file they list: `.db` indexes into the
/// download folder, public-domain `.pdf` books into `pdf_dir`. Returns how many
/// files were fetched.
pub async fn download_indexes() -> Result<usize> {
    let download_dir = storage::download_dir();
    let pdf_dir = storage::pdf_dir();
    std::fs::create_dir_all(&download_dir)?;
    std::fs::create_dir_all(&pdf_dir)?;
    let client = Client::new();

    // Indexes are required: a failure here surfaces to the user.
    let mut count = fetch_manifest(&client, "index.txt", &download_dir, ".db", false).await?;

    // Public-domain PDFs are optional: a missing manifest (or any error) just
    // means there are none to add, so it must not fail the whole reload.
    match fetch_manifest(&client, "pdfindex.txt", &pdf_dir, ".pdf", true).await {
        Ok(n) => count += n,
        Err(e) => log::info!("no published PDFs ({e})"),
    }
    Ok(count)
}

/// Fetch `manifest` (one filename per line) and download each entry ending in
/// `ext` (case-insensitive) into `dir`. When `skip_existing`, a file already on
/// disk is left untouched — so Reload never re-fetches a large PDF it has.
/// Returns how many files were fetched.
async fn fetch_manifest(
    client: &Client,
    manifest: &str,
    dir: &Path,
    ext: &str,
    skip_existing: bool,
) -> Result<usize> {
    let list = client
        .get(format!("{BASE_URL}/{manifest}"))
        .send()
        .await?
        .error_for_status()?
        .text()
        .await?;

    let mut count = 0;
    for line in list.lines() {
        let name = line.trim();
        if name.is_empty() || !name.to_ascii_lowercase().ends_with(ext) {
            continue;
        }
        let dest = dir.join(name);
        if skip_existing && dest.exists() {
            continue;
        }
        let url = format!("{BASE_URL}/{name}");
        match download_to(client, &url, &dest).await {
            Ok(()) => count += 1,
            Err(e) => log::warn!("failed to download {name}: {e}"),
        }
    }
    Ok(count)
}
